name: chapitas-qoe
region: nyc
domains:
  - domain: chapitas.qoe.cl
    type: PRIMARY
    zone: qoe.cl
    minimum_tls_version: "1.3"
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
static_sites:
  - name: chapitas-web
    environment_slug: html
    github:
      repo: fdovasquez/chapitas-qoe
      branch: main
      deploy_on_push: true
    index_document: index.html
